name: Zip Root Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip_files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a ZIP file containing all files in the root directory
      - name: Create ZIP file
        run: |
          echo "Creating ZIP file..."
          mkdir -p /tmp/grass
          cp qmm.yaml /tmp/grass
          cp qmm.png /tmp/grass
          rsync -a --exclude={'.gitignore'} grass.quail/ /tmp/grass/
          cd /tmp
          REPO_NAME=$(basename ${{ github.repository }})
          echo "Zipping files..."
          zip -r $REPO_NAME.zip grass
          mv $REPO_NAME.zip $GITHUB_WORKSPACE/$REPO_NAME.zip

      # Upload the ZIP file as an artifact
      - name: Upload ZIP file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository }}
          path: $REPO_NAME.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.ref == 'refs/heads/main'
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "${{ github.repository }}"
          files: |
            $REPO_NAME.zip
